include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Responsible for Documentation
    public_member_api_docs: true
    # Responsible for Sort pubspec.ymal packages
    sort_pub_dependencies: true
    # Avoid defining a one-member abstract class
    one_member_abstracts: false
    # Responsible for add constant while its needed
    constant_identifier_names: false
    # Responsible for package imports
    always_use_package_imports: true
    depend_on_referenced_packages: false
    # Responsible for write multiple line documentation
    lines_longer_than_80_chars: false
analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - lib/graphql/_generated_/*.gql.dart
    - lib/firebase_options*.dart
    - lib/graphql/_generated_/*.dart
  errors:
    invalid_annotation_target: ignore