name: flutter_basics
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.1.0
  get_it: ^8.0.3
  go_router: ^14.7.2
  logger: ^2.5.0
  multi_value_listenable_builder: ^0.0.2
  syncfusion_flutter_sliders: ^28.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-SemiBold.ttf
           weight: 400
         - asset: assets/fonts/Inter-Regular.ttf
           weight: 500
         - asset: assets/fonts/Inter-Medium.ttf
           weight: 600
         - asset: assets/fonts/Inter-Bold.ttf
           weight: 700
         - asset: assets/fonts/Inter-ExtraBold.ttf
           weight: 800
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Thin.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 800
         - asset: assets/fonts/Montserrat-ExtraBold.ttf
           weight: 900
#     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
